#pragma once

enum {
	ENCODING_ANSI = 0,
	ENCODING_UTF8,
	ENCODING_UTF8_BOM,
	ENCODING_UTF16_BE,
	ENCODING_UTF16_LE,
	ENCODING_UTF16_BE_BOM,
	ENCODING_UTF16_LE_BOM,
	ENCODING_OEM,
	ENCODING_MAC,
	ENCODING_COUNT
};
